CREATE TABLE IF NOT EXISTS queue (
  msg_id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  enqueued_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  vt TIMESTAMP WITH TIME ZONE NOT NULL,
  message JSONB
);
